version: "3"

services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_PASSWORD: root  
      MYSQL_DATABASE: vendas-pos-graduacao
    ports:
      - "3310:3306"
    restart: always